# Generated by Django 4.2 on 2024-09-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Fabric', 'Fabric'), ('Tent', 'Tent'), ('General Sticker', 'General Sticker'), ('Computer Die-Cut Sticker', 'Computer Die-Cut Sticker'), ('Mounting Box', 'Mounting Box'), ('Display System', 'Display System'), ('Poster & Lightbox', 'Poster & Lightbox'), ('Backdrop', 'Backdrop')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('features', models.TextField(blank=True, help_text='Enter features separated by commas.')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
